language: java
jdk:
- openjdk8
- openjdk10
- openjdk11
sudo: required
env:
  global:
  - GH_PROJECT_NAME: IntelliJ-Key-Promoter-X
  - GIT_AUTHOR_NAME: TravisCI
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - CI_HOME=`pwd`
  - GRADLE_USER_HOME=`pwd`/.gradle
before_script:
- chmod +x gradlew
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: SdCmZ1toP3b/jPvI0IbBK9n3k8ljpOW58WezEttU+z1fda4M+wYHqJnd/ovehLDsBra2Pa0VoC08W3Ba7k4Bm8+bNLjrQyq+X5lzdL4AW4H4Bm/608rH+3IUNnCtUWSx/La4Ul9wxp0cVf0DLx64boRyC/ao5G+JI6qkNkwPiv7/rmJ6dpxBCMdedIQSAAarlhx8cnge2mAUtiKVXAmM36fMDzvq0q1M2VQGXSyxHpzUu9VUxsc6u4CfnJKQiK1E6KfCAnd0WICRxzV2Kt6CIkJyF+7eVdQw11sDvIkSxGri63VNO3Hec8lDJoTHda/tfDmbz8PU1DeLzpiMg4VaFaVKjI22yI2rjaqdxNe2pN1JPuAzkR1rEdPvn54OC228UOkKiojKLG+hnHRrdUs2bxFHexFYzTzPJaYuOEwUTOizX4rJhVC039w/jQHb3py2iGKaoco+hKqa64ibStwEZW6o0Y3/yHVZG5dprsfpVN66dRkuTeMNvXus83BC/IR3WQk6v1S8YjrM3DkIr6zopOSrRQ5WI7A9S8yAsuSQF8oSeLGjA9ODcDJ36MzvvUKhS7yzw4hEZOTXrR9sYvri5JV0Oudgj3CuZ9udSBMSgNVtKLxlBL1t03YMyh0FIVL/Pz+Fxzhvql8xzo2UdnsBZvQ4m6ZocwYe415PWh3svgU=
  file: "$CI_HOME/build/distributions/Key-Promoter-X*.zip"
  on:
    repo: halirutan/IntelliJ-Key-Promoter-X
    all_branches: true
    tags: true

